### ISSUE TITLE
segmentation标注能使用吗？

### ISSUE THREAD

**Issue by moontsar** [amazon-research/bigdetection#15]
请问BigDetection标注中的segmentation能使用吗？想使用BigDetection训练实例分割模型

**Comment by bryanyzhu** [comment]
@cailk

**Comment by cailk** [comment]
> 请问BigDetection标注中的segmentation能使用吗？想使用BigDetection训练实例分割模型

非常抱歉，回复的比较晚了！目前BigDetection还不支持segmentation，我们只处理了bounding box标注信息，segmentation
会考虑在之后的版本处理并加进去～
