### ISSUE TITLE
why set workers_per_gpu=0

### ISSUE THREAD

**Issue by czczup** [amazon-research/bigdetection#16]
Hi, thanks for your awesome work! I have a question about the dataloader of BigDetection, why set `workers_per_gpu=0` in the dataloader? The current code requires 0.2-0.3s to load data in my experiment, I hope to use more workers to improve training efficiency, but set `workers_per_gpu>0` seems to hang the code.

**Comment by bryanyzhu** [comment]
Thank you, the hanging issue could be caused by multiple reasons, which you might find solutions in MMdet issues. In general, it is likely because small shared memory and multi-threading. I suggest to install the latest MMdet to see if the issue persists.

**Comment by czczup** [comment]
> Thank you, the hanging issue could be caused by multiple reasons, which you might find solutions in MMdet issues. In general, it is likely because small shared memory and multi-threading. I suggest to install the latest MMdet to see if the issue persists.

I solved it. Thank you for your reply.
