### ISSUE TITLE
Class Name Wrong

### ISSUE THREAD

**Issue by YangYangGirl** [amazon-research/bigdetection#6]
Thanks for your great work. I visualize your Train and Val dataset using the mmdetection tool in "tools/misc/browse_dataset.py", but the people are wrongly labeled as "ice cream". Please find the example below. 

![Uploading thumbnail_objects365_v2_00900062.jpeg…]()

**Comment by bryanyzhu** [comment]
Hi, @cailk has fixed the problem in this PR #7 . Please let us know if the problem persists, thank you.
