### ISSUE TITLE
Config for Cascade R-CNN

### ISSUE THREAD

**Issue by dzhurak** [amazon-research/bigdetection#9]
Hello, the config for Cascade R-CNN is missing. I tried to use the one from [Detectron2](https://github.com/facebookresearch/detectron2/blob/main/configs/Misc/cascade_mask_rcnn_R_50_FPN_3x.yaml) without the mask head but got the following error
```RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
        Missing key(s) in state_dict: "backbone.fpn_lateral2.weight", "backbone.fpn_lateral2.bias", "backbone.fpn_output2.weight", "backbone.fpn_output2.bias".
        Unexpected key(s) in state_dict: "backbone.top_block.p6.weight", "backbone.top_block.p6.bias", "backbone.top_block.p7.weight", "backbone.top_block.p7.bias".
        size mismatch for proposal_generator.rpn_head.objectness_logits.weight: copying a param with shape torch.Size([9, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
        size mismatch for proposal_generator.rpn_head.objectness_logits.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([3]).
        size mismatch for proposal_generator.rpn_head.anchor_deltas.weight: copying a param with shape torch.Size([36, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([12, 256, 1, 1]).
        size mismatch for proposal_generator.rpn_head.anchor_deltas.bias: copying a param with shape torch.Size([36]) from checkpoint, the shape in current model is torch.Size([12])
```

**Comment by bryanyzhu** [comment]
@cailk any thought?

**Comment by cailk** [comment]
> Hello, the config for Cascade R-CNN is missing. I tried to use the one from [Detectron2](https://github.com/facebookresearch/detectron2/blob/main/configs/Misc/cascade_mask_rcnn_R_50_FPN_3x.yaml) without the mask head but got the following error
> 
> ```
>         Missing key(s) in state_dict: "backbone.fpn_lateral2.weight", "backbone.fpn_lateral2.bias", "backbone.fpn_output2.weight", "backbone.fpn_output2.bias".
>         Unexpected key(s) in state_dict: "backbone.top_block.p6.weight", "backbone.top_block.p6.bias", "backbone.top_block.p7.weight", "backbone.top_block.p7.bias".
>         size mismatch for proposal_generator.rpn_head.objectness_logits.weight: copying a param with shape torch.Size([9, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 256, 1, 1]).
>         size mismatch for proposal_generator.rpn_head.objectness_logits.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([3]).
>         size mismatch for proposal_generator.rpn_head.anchor_deltas.weight: copying a param with shape torch.Size([36, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([12, 256, 1, 1]).
>         size mismatch for proposal_generator.rpn_head.anchor_deltas.bias: copying a param with shape torch.Size([36]) from checkpoint, the shape in current model is torch.Size([12])
> ```

Hi, sorry for the late reply. We just updated the configurations for detectron2-based models. To better reproduce these results, I suggest you use the project of [CenterNet2](https://github.com/xingyizhou/CenterNet2) as we are also running upon this codebase~
